train:
	CUDA_VISIBLE_DEVICES=0,1,2 bash tools/dist_train.sh configs/skeleton/stgcnpp/stgcnpp_8xb16-joint-motion-u100-80e_ntu60-xsub-keypoint-2d.py 3

train2:
	CUDA_VISIBLE_DEVICES=0,1,2,3 bash tools/dist_train.sh configs/skeleton/stgcnpp/stgcnpp_8xb16-joint-u100-80e_ntu60-xsub-keypoint-2d.py 3


